"""init payment tables

Revision ID: 6ace02c5072b
Revises: 
Create Date: 2026-02-11 21:48:45.848556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ace02c5072b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_no', sa.String(length=30), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('booking_public_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_public_id', sa.String(length=25), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ISSUED', nullable=True),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.String(length=25), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('booking_public_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_payment_booking_id', 'payment_transactions', ['booking_id'], unique=False)
    op.create_index('idx_payment_gateway', 'payment_transactions', ['gateway'], unique=False)
    op.create_index('idx_payment_transaction_id', 'payment_transactions', ['transaction_id'], unique=False)
    op.create_table('payment_webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_payment_webhook_gateway', 'payment_webhooks', ['gateway'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('refund_id', sa.String(length=25), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gateway_refund_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_index('idx_payment_webhook_gateway', table_name='payment_webhooks')
    op.drop_table('payment_webhooks')
    op.drop_index('idx_payment_transaction_id', table_name='payment_transactions')
    op.drop_index('idx_payment_gateway', table_name='payment_transactions')
    op.drop_index('idx_payment_booking_id', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_table('invoices')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
