"""alter webhooks tables

Revision ID: e2a54731bf0e
Revises: ff57957a62e9
Create Date: 2026-02-16 22:50:49.824767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2a54731bf0e'
down_revision: Union[str, Sequence[str], None] = 'ff57957a62e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_webhooks_event_id_key'), 'payment_webhooks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('payment_webhooks_event_id_key'), 'payment_webhooks', ['event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
