"""alter payment tables

Revision ID: ff57957a62e9
Revises: e2f9943da887
Create Date: 2026-02-15 14:36:27.975747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff57957a62e9'
down_revision: Union[str, Sequence[str], None] = 'e2f9943da887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('refund_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id')
    )
    op.create_table('credit_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('refund_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['refund_transaction_id'], ['refund_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_note_number'),
    sa.UniqueConstraint('refund_transaction_id')
    )
    op.drop_table('refunds')
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('pdf_url', sa.Text(), nullable=True))
    op.add_column('payment_transactions', sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payment_transactions', sa.Column('refund_status', sa.String(length=20), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'refund_status')
    op.drop_column('payment_transactions', 'refund_amount')
    op.drop_column('invoices', 'pdf_url')
    op.drop_column('invoices', 'tax_amount')
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refund_id', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('gateway_refund_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey')),
    sa.UniqueConstraint('refund_id', name=op.f('refunds_refund_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('credit_notes')
    op.drop_table('refund_transactions')
    # ### end Alembic commands ###
